### ISSUE TITLE
PS4 PS2 Classics Gui - Fatal Crash on No Audio Device Present (First Boot)

### ISSUE THREAD

**Issue by ghost** [xXxTheDarkprogramerxXx/PS3Tools#13]
xXxTheDarkprogrammerxXx,

     I apologize for the two nonsense emails I sent you. You may completely disregard them. By default I have my laptop speakers disabled so I had technically had no audio device present upon launching the program after the update. It appears that the program tries to play audio and when it fails to play the program does not know what to do and crashes or stops responding. It should be fixable by adding a check for a usable audio device on launch and if none are found to automatically disable the sounds.
     The program will still launch normally without an audio device but will present a pop-up box stating ("BadDeviceId calling waveOutOpen") and then appears to operate normally. The fatal crash is only on first launch.

Regards,
Anonamous

**Comment by xXxTheDarkprogramerxXx** [comment]
Hi i did read your email ... i didnt get the second one(i didnr get a notice i see it here now) ... i will add a check soon for this 

Also the app has been playing an audio file since the new ui but i will check all of this for you

**Comment by ghost** [comment]
Ok, thank you. It only happens the first time it's launched when the option for the tutorial comes up.

**Comment by xXxTheDarkprogramerxXx** [comment]
Is this still an issue for you?

**Comment by ghost** [comment]
I cloned the repo and am running the application in 'PS3Tools\PS4 PS2 Classis GUI\PS4 PS2 Classics Gui (WPF)\bin\Debug'

With all devices in windows sound playback set to disabled:

It will launch and can make the ps2 classic successfully. However it will immediately crash upon clicking the sound icon in the top right, entering the settings menu, or entering the how to use menu.

**Comment by xXxTheDarkprogramerxXx** [comment]
@PGAnonamous  thats very strange .... can you attach a debugger to it and see why its crashing

**Comment by ghost** [comment]
Here are the details of the crash.
```
NAudio.MmException
  HResult=0x80131500
  Message=BadDeviceId calling waveOutOpen
  Source=NAudio
  StackTrace:
   at NAudio.Wave.WaveOut.Init(IWaveProvider waveProvider)
   at PS4_PS2_Classics_Gui__WPF_.SoundClass.<>c.<PlayPS4Sound>b__7_3() in C:\Users\3deEchelon\Documents\GitHub\PS3Tools\PS4 PS2 Classis GUI\PS4 PS2 Classics Gui (WPF)\SoundClass.cs:line 167
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by xXxTheDarkprogramerxXx** [comment]
@PGAnonamous  i did some digging have you updated your drivers recently ?

in the mean time it seems to be when initialization happens on the wave drivers .... i will add error handling here for you

**Comment by ghost** [comment]
I actually have the sound device intentionally disabled in the sounds panel and the audio driver disabled in the device manager along with my webcam for reasons.

The same exception should occur if someone were to have an audio device or sound card that was broken which is the reason I submitted the issue.

**Comment by xXxTheDarkprogramerxXx** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [PS2 Classics Gui](https://trello.com/c/37jjtYg9/7-ps2-classics-gui)

**Comment by xXxTheDarkprogramerxXx** [comment]
@PGAnonamous 
Please try again in a few minutes as i will be pushing an update soon

**Comment by ghost** [comment]
I ran it this morning under a couple cases and it ran ok but crashes when I tried to close the tutorial. I will run the debugger and reply again with an update after class this morning.

**Comment by xXxTheDarkprogramerxXx** [comment]
@PGAnonamous  thanks for the reply let me know an update was made about 2 hours ago

**Comment by ghost** [comment]
I pulled it this morning. Unfortunately the cause of the crash is the same

```
NAudio.MmException
  HResult=0x80131500
  Message=BadDeviceId calling waveOutOpen
  Source=NAudio
  StackTrace:
   at NAudio.Wave.WaveOut.Init(IWaveProvider waveProvider)
   at PS4_PS2_Classics_Gui__WPF_.SoundClass.<>c.<PlayPS4Sound>b__7_3() in C:\Users\3deEchelon\Documents\GitHub\PS3Tools\PS4 PS2 Classis GUI\PS4 PS2 Classics Gui (WPF)\SoundClass.cs:line 169
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```
